// Map of common words to their corresponding single sign images
export const COMMON_SIGNS = {
  'hi': '/signs/common/hi.png',
  'hello': '/signs/common/hi.png', // Same sign as 'hi'
  // 'me': '/signs/common/me.png',
  // 'i': '/signs/common/me.png',
  // 'you': '/signs/common/you.png',
  // 'he': '/signs/common/he.png',
  // 'she': '/signs/common/she.png',
  // 'it': '/signs/common/it.png',
  // 'we': '/signs/common/we.png',
  // 'us': '/signs/common/us.png',
  // 'they': '/signs/common/they.png',
  // 'who': '/signs/common/who.png',
  // 'what': '/signs/common/what.png',
  'bathroom': '/signs/common/bathroom.png',
  // 'house': '/signs/common/house.png',
  // 'car': '/signs/common/car.png',
  // 'book': '/signs/common/book.png',
  // 'chair': '/signs/common/chair.png',
  // 'food': '/signs/common/food.png',
  // 'water': '/signs/common/water.png',
  // 'school': '/signs/common/school.png',
  // 'friend': '/signs/common/friend.png',
  // 'money': '/signs/common/money.png',
  // 'mother': '/signs/common/mother.png',
  'father': '/signs/common/father.png',
  // 'brother': '/signs/common/brother.png',
  // 'sister': '/signs/common/sister.png',
  // 'big': '/signs/common/big.png',
  // 'small': '/signs/common/small.png',
  // 'happy': '/signs/common/happy.png',
  'yes': '/signs/common/yes.png',
  'no': '/signs/common/no.png',
  // 'stop': '/signs/common/stop.png',
  // 'go': '/signs/common/go.png',
  // 'thank you': '/signs/common/thank_you.png',
  // 'sorry': '/signs/common/sorry.png',
  // 'please': '/signs/common/please.png'
};