// Map of characters to their corresponding sign language images
export const SIGN_IMAGES = {
  a: '/signs/a.png',
  b: '/signs/b.png',
  c: '/signs/c.png',
  d: '/signs/d.png',
  e: '/signs/e.png',
  f: '/signs/f.png',
  g: '/signs/g.png',
  h: '/signs/h.png',
  i: '/signs/i.png',
  j: '/signs/j.png',
  k: '/signs/k.png',
  l: '/signs/l.png',
  m: '/signs/m.png',
  n: '/signs/n.png',
  o: '/signs/o.png',
  p: '/signs/p.png',
  q: '/signs/q.png',
  r: '/signs/r.png',
  s: '/signs/s.png',
  t: '/signs/t.png',
  u: '/signs/u.png',
  v: '/signs/v.png',
  w: '/signs/w.png',
  x: '/signs/x.png',
  y: '/signs/y.png',
  z: '/signs/z.png'
};